order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('customer', views.find_customer, name='add-customer'),
    path('register-customer',
         views.add_customer,
         name='register-customer'),
    path('paying-amount', views.add_paying_amount, name='paying-amount'),
    path('create-order', views.order_create, name='create-order'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('cart-detail', views.cart_detail, name='cart_detail'),
    path('<int:product_id>/add-to-cart/',
         views.cart_add,
         name='cart_add'),
]

rfc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('products/', include('product.urls')),
    path('order/', include('order.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
]

product/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200,
     	                    db_index=True)
    slug = models.SlugField(max_length=200,
                            db_index=True,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    def __str__(self):
    	return self.name

    def get_absolute_url(self):
        return reverse('product:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
		                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:product_detail',
                       args=[self.id, self.slug])

product/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                               choices=PRODUCT_QUANTITY_CHOICES,
                               coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .models import Category, Product
from .forms import CartAddProductForm
from .cart import Cart
# from django.http import HttpResponse
# Create your views here.


def product_list(request):
    categories = Category.objects.all()
    return render(request,
                  'product/list.html',
                  {'categories': categories})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('product:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('product:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                       initial={'quantity': item['quantity'],
                                                'update': True})
    return render(request, 'product/cart-detail.html', {'cart': cart})

templates/product/cart-detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Your shopping cart
{% endblock %}
{% block content %}
<h1>Your shopping cart</h1>
<table>
	<thead>
		<tr>
			<th>Image</th>
			<th>Product</th>
			<th>Quantity</th>
			<th>Remove</th>
			<th>Unit price</th>
			<th>Price</th>
		</tr>
	</thead>
<tbody>
	{% for item in cart %}
	{% with product=item.product %}
	<tr>
		<td>
		<a href="{{ product.get_absolute_url }}">
		<img src="{% if product.image %}{{ product.image.url
		}}{% else %}{% static "img/no_image.png" %}{% endif %}">
		</a>
		</td>
		<td>{{ product.name }}</td>
		<td>
			<form action="{% url "product:cart_add" product.id %}" method="post">
			{{ item.update_quantity_form.quantity }}
			{{ item.update_quantity_form.update }}
			<input type="submit" value="Update">
			{% csrf_token %}
			</form>
		</td>

		<td><a href="">Remove</a></td>
		<td>${{ item.price }}</td>
		<td>${{ item.total_price }}</td>
	</tr>
	{% endwith %}
	{% endfor %}
	<tr>
		<td>Total</td>
		<td colspan="4"></td>
		<td class="num">${{ cart.get_total_price }}</td>
	</tr>
</tbody>
</table>
<p class="text-right">
	<a href="{% url 'product:product_list' %}" class="btn">Continue shopping
	 </a>
	<a href="{% url 'order:add-customer' %}" class="btn">
	   Checkout
	</a>
</p>
{% endblock %}

templates/product/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}  {% endblock %}

{% block content %}


<h1>{{ product.name }}</h1>
{{ product.category }}
<p>Rs {{ product.price }}</p>

<form action="{% url "product:cart_add" product.id %}" method="post">
	{{ cart_product_form }}
	{% csrf_token %}
	<input  type="submit" value="Add to cart" class="btn">
</form>
{{ product.description|linebreaks }}
{% endblock %}

templates/product/list.html
{% extends "base.html" %}
{% load static %}
{% block title %} RFC products {% endblock %}

{% block content %}
<h2>Available Product</h2>

{% for category in categories %}


<h3>{{ category.name }}</h3>

{% for product in category.products.all %}
<div class="row">
        <div class="col s12 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">{{ product.name }}</span>
              <p>{{ product.description }}</p>
              <p>{{ product.price }}</p>
            </div>
            <div class="card-action">
              <a href="{% url 'product:product_detail' product.id product.slug %}">DETAIL</a>             
            </div>
          </div>
        </div>
      </div>
{% endfor %}
{% endfor %}
{% endblock %}
 