dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.order_list, name='dashboard'),
    path('order-detail/<int:order_id>',
         views.order_detail,
         name='order_detail'),
    path('customer-detail/<int:customer_id>',
         views.customer_detail,
         name='customer_detail'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('cart-detail', views.cart_detail, name='cart_detail'),
    path('<int:product_id>/add-to-cart/',
         views.cart_add,
         name='cart_add'),
]

rfc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('products/', include('product.urls')),
    path('order/', include('order.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
	<title>{% block title %}{% endblock %}</title>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body>

 <nav>
    <div class="nav-wrapper">
      <a href="{%url 'home' %}" class="brand-logo">RFC</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="{% url 'product:product_list' %}">Products</a></li>
        <li><a href="{%url 'dashboard:dashboard' %}">Dashboard</a></li>
      </ul>
    
 </div>
  </nav>

<div class="container">
 {% with total_items=cart|length %}
{% if cart|length > 0 %}
Cart:
<a href="{% url 'product:cart_detail' %}">
{{ total_items }} item{{ total_items|pluralize }},
${{ cart.get_total_price }}
</a>
{% else %}
EMPTY CART.
{% endif %}
{% endwith %}



<main>
{% block content %}
{% endblock %}
<br>
<br>
<br>
</main>

</div>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}
RFC Fruits
{% endblock %}

{% block content %}
<h1>RFC Fruits </h1>

{% endblock %}