dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.order_list, name='dashboard'),
    path('order-detail/<int:order_id>',
         views.order_detail,
         name='order_detail'),
    path('customer-detail/<int:customer_id>',
         views.customer_detail,
         name='customer_detail'),
]

rfc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('products/', include('product.urls')),
    path('order/', include('order.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render, get_object_or_404
from order.models import Order, Customer

# Create your views here.


def order_list(request):
    orders = Order.objects.all()
    return render(request, 'dashboard/order-history.html', {'orders': orders})


def order_detail(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    return render(request, 'dashboard/order-detail.html', {'order': order})


def customer_detail(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    orders = customer.orders.all()
    return render(request,
                  'dashboard/customer-detail.html',
                  {'customer': customer, 'orders': orders})

templates/dashboard/customer-detail.html
{% extends "dashboard/dashboard_base.html" %}
{% load static %}
{% block title %}
RFC Fruits
{% endblock %}

{% block dashboard_content %}
 <h3>customer detail</h3>
 <ul>
 <li> NAME : {{customer.name}}</li>
 <li>PHONE NUMBER: {{customer.phone_number}}</li>
<li>ADDRESS: {{customer.address}}</li>
</ul>
<h3>orders history</h4>
<table>
<thead>
	<th>Order Number</th>
	<th> Date</th>
	<th> Payment Status</th>
</thead>


{% for order in orders %}
<tr>
<td>
<a href="{% url 'dashboard:order_detail' order.id %}">{{ order.id}}</a> 
</td> 
<td>
 {{order.created}}
</td>
 <td>
{% if order.is_unpaid %}UNPAID {% else %} CLEAR {% endif %}
</td>

</tr>
{% endfor %}
</table>
{% endblock %}

templates/dashboard/dashboard_base.html
{% extends "base.html" %}
{% load static %}
{% block title %}
RFC Fruits
{% endblock %}

{% block content %}
<h1>Dashboard</h1>
<h2>Manage</h2>
<a href="{%url 'dashboard:dashboard' %}">ORDERS</a><br>
<a href="">unpaid orders</a><br>
<a href="">CUSTOMER</a><br>
<a href="">unpaid Customer</a><br>
<a href="">Most Frequent</a><br>
<a href="">Expenditure</a><br>


{% block dashboard_content %}
{% endblock %}
{% endblock %}

templates/dashboard/order-detail.html
{% extends "dashboard/dashboard_base.html" %}
{% load static %}
{% block title %}
RFC Fruits
{% endblock %}

{% block dashboard_content %}
<h3>Oder Details</h3>
<h4>Customer</h4>
<ul>
<li> NAME:  {{ order.customer.name}} </li>
<li>  PHONE NUMBER: {{ order.customer.phone_number}} </li>
<li> ADDRESS: {{ order.customer.address}}</li>
</ul>
<h4>items</h4>
<table>


<thead>
	<th>Product</th>
	<th>Cost</th>
	<th>Quantity</th>
</thead>
<tbody>
{% for item in order.items.all %}
<tr>
<td> {{item.product}} </td>
<td> {{item.price}} </td>
 <td> {{item.quantity}} </td>
</tr>
{% endfor %}
</table>
<h4>Payment Detail</h4>
Total Cost: {{order.get_total_cost}} 
Paid Amount: {{order.paid_amount}}
{% endblock %}

templates/dashboard/order-history.html
{% extends "dashboard/dashboard_base.html" %}
{% load static %}
{% block title %}
RFC Fruits
{% endblock %}

{% block dashboard_content %}

<table>
<thead>
	<th>Order Number</th>
	<th> Date</th>
	<th> Customer</th>
	<th>Amount</th>
	<th>Paid Amount</th>
</thead>

{% for order in orders %}
<tr>
<td>
<a href="{% url 'dashboard:order_detail' order.id %}">{{ order.id}}</a>
</td>
<td>
 {{order.created}}
 </td>
 <td>
<a href="{% url 'dashboard:customer_detail' order.customer.id %}">{{order.customer.name}}</a>
</td>
<td>
{{order.get_total_cost }}
</td>
<td>
{{ order.paid_amount }}<br>
</td>
{% endfor %}
</tr>
</table>
{% endblock %}