order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('customer', views.find_customer, name='add-customer'),
    path('register-customer',
         views.add_customer,
         name='register-customer'),
    path('paying-amount', views.add_paying_amount, name='paying-amount'),
    path('create-order', views.order_create, name='create-order'),
]

rfc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('products/', include('product.urls')),
    path('order/', include('order.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
]

order/models.py
from django.db import models
from product.models import Product

# Create your models here.


class Customer(models.Model):
    name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=10, unique=True)
    address = models.CharField(max_length=250)
    location = models.CharField(max_length=20)

    def __str__(self):
        return '{}'.format(self.name)


class Order(models.Model):
    customer = models.ForeignKey(Customer,
                                 on_delete=models.CASCADE,
                                 related_name='orders')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid_amount = models.PositiveIntegerField()

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    def is_unpaid(self):
        if self.paid_amount < self.get_total_cost():
            return True

    def get_due_amount(self):
        return self.get_total_cost() - self.paid_amount


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity


class Expenditure(models.Model):
    amount = models.PositiveIntegerField()
    description = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'expenditure {}'.format(self.id)

order/forms.py
from django import forms
from .models import Customer


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'


class FindCustomerForm(forms.Form):
    phone_number = forms.CharField()

order/views.py
from django.shortcuts import render, get_object_or_404
from product.cart import Cart
from .forms import CustomerForm
from .models import Order, OrderItem, Customer

# Create your views here.


def order_create(request):
    cart = Cart(request)
    new_order = request.session['order']
    order = Order.objects.create(customer=new_order['customer'],
                                 paid_amount=new_order['paid_amount'])
    for item in cart:
        OrderItem.objects.create(order=order,
                                 product=item['product'],
                                 price=item['price'],
                                 quantity=item['quantity'])
    cart.clear()
    new_order.clear()
    return render(request, 'order/order-created.html')


def find_customer(request):
    cart = Cart(request)
    form = CustomerForm()
    return render(request,
                  'order/add-customer.html',
                  {'cart': cart, 'form': form})


def add_customer(request):
    cart = Cart(request)
    if request.session['order']:
        request.session['order'].clear()
    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            customer = form.save()
    else:
        phone_number = request.GET['phone']
        customer = get_object_or_404(Customer, phone_number=phone_number)
    request.session['order'] = {'customer': customer,
                                'paid_amount': ""}
    return render(request, 'order/add-paid-amount.html',
                  {'cart': cart, 'customer': customer})


def add_paying_amount(request):
    paid_amount = request.GET['amount']
    request.session['order']['paid_amount'] = paid_amount
    request.session.modified = True
    new_order = request.session['order']
    cart = Cart(request)
    return render(request,
                  'order/confirm-order.html',
                  {'cart': cart, 'order': new_order})

templates/order/add-customer.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Cart Customer
{% endblock %}
{% block content %}
<h2>Place Order</h2>
<table>
	<thead>
		<tr>
			<th>Product</th>
			<th>Quantity</th>
			<th>Unit price</th>
			<th>Price</th>
		</tr>
	</thead>
    <tbody>
	{% for item in cart %}
	{% with product=item.product %}
	    <tr>
			<td>{{ product.name }}</td>
			<td>{{ item.quantity }}</td>
			<td>${{ item.price }}</td>
			<td>${{ item.total_price }}</td>
		</tr>
		{% endwith %}
		{% endfor %}
		<tr>
			<td><b> Total</b></td>
			<td></td>
			<td><b>${{ cart.get_total_price }}</b></td>
		</tr>
    </tbody>
</table>

<p> 
 <h4>Find Customer</h4>

<form action="{% url 'order:register-customer' %}" method="get">
		    <p><label for="id_phone">Phone Number:</label> 
			<input type="text" name="phone" maxlength="10" required id="id_phone" /></p>			
		    <input type="submit" value="Find" class="btn">
</form>
</p>


<p>
 <h4>New Customer</h4>
	<form action="{% url 'order:register-customer' %}" method="post">
			{{ form.as_p }}		
			<input type="submit" value="Register" class="btn">
			{% csrf_token %}
	</form>
</p>

{% endblock %}

templates/order/add-paid-amount.html
{% extends "base.html" %}
{% load static %}
{% block title %}
   Order Payment
{% endblock %}
{% block content %}
<h1>Order</h1>
<h2>Cart</h2>
<table>
	<thead>
		<tr>
			<th>Product</th>
			<th>Quantity</th>
			<th>Unit price</th>
			<th>Price</th>
		</tr>
	</thead>
    <tbody>
	{% for item in cart %}
	{% with product=item.product %}
	    <tr>
			<td>{{ product.name }}</td>
			<td>{{ item.quantity }}</td>
			<td>${{ item.price }}</td>
			<td>${{ item.total_price }}</td>
		</tr>
		{% endwith %}
		{% endfor %}
		<tr>
			<td>Total</td>
			<td></td>
			<td>${{ cart.get_total_price }}</td>
		</tr>
    </tbody>
</table>
<h2>Customer</h2>
<p>
	<table>
	<tbody>
	<tr>
	<td> Name : </td> <td> {{ customer.name }}  </td>
	</tr>
	<tr>
	<td>Phone Number:</td> <td> {{ customer.phone_number }}</td>
	</tr>
	<tr>
	<td> Address:</td> <td>{{ customer.address }}</td>
	</tr>
	</tbody>
	</table>
</p>

<h2>Amount Paying </h2>
<form action="{% url 'order:paying-amount' %}" method="get">
		    <p><label for="id_amount">Amount:</label> 
			<input type="text" name="amount" maxlength="5" required id="id_amount" /></p>			
		    <input type="submit" value="Add" class="btn">
</form>

{% endblock %}

templates/order/confirm-order.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Confirm Order
{% endblock %}
{% block content %}
<h1>Order</h1>
<h2>Cart</h2>
<table>
	<thead>
		<tr>
			<th>Product</th>
			<th>Quantity</th>
			<th>Unit price</th>
			<th>Price</th>
		</tr>
	</thead>
    <tbody>
	{% for item in cart %}
	{% with product=item.product %}
	    <tr>
			<td>{{ product.name }}</td>
			<td>{{ item.quantity }}</td>
			<td>${{ item.price }}</td>
			<td>${{ item.total_price }}</td>
		</tr>
		{% endwith %}
		{% endfor %}
		<tr>
			<td>Total</td>
			<td></td>
			<td>${{ cart.get_total_price }}</td>
		</tr>
    </tbody>
</table>
<h2>Customer</h2>
<p>
<table>
	<tbody>
	<tr>
	<td> Name : </td> <td> {{ order.customer.name }}  </td>
	</tr>
	<tr>
	<td>Phone Number:</td> <td> {{ order.customer.phone_number }}</td>
	</tr>
	<tr>
	<td> Address:</td> <td>{{ order.customer.address }}</td>
	</tr>
	</tbody>
	</table
</p>

<h2>Amount Paying </h2>

{{order.paid_amount}}

<p><a href="{% url 'order:create-order' %}" class="btn">CONFIRM</a></p>

{% endblock %}

templates/order/order-created.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Confirm Order
{% endblock %}
{% block content %}
<h2>Order created Successfully !!!</h2>
<h3>generate bill </h3>
{% endblock %}